mysql_root_password: "1234"
mysql_root_user: "root"
mysql_user: "ezekiel"
db_name: "ezekieldb"
db_user: "ezekiel"
user_pass: "1234"
http_conf: "exam.conf"
http_port: "80"
https_port: "443"
ssh_port: "22"
mysql_port: "3306"
